import type { NextPage } from 'next'
import { useState, useEffect, ReactNode } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type TicketList = {
  id: number;
  ticketNumber: number;
  result: boolean;
  checkDatetime: String;
}

const Home: NextPage = () => {

  const [tickets, setTickets] = useState<TicketList[]>([]);

  useEffect(() => {
    setTickets([
      {
        id: 1,
        ticketNumber: 123456,
        result: false,
        checkDatetime: "23/08/2022 14:20"
      },
      {
        id: 2,
        ticketNumber: 345678,
        result: true,
        checkDatetime: "23/08/2022 14:20"
      },
      {
        id: 3,
        ticketNumber: 222333,
        result: true,
        checkDatetime: "23/08/2022 14:20"
      },
      {
        id: 4,
        ticketNumber: 123456,
        result: false,
        checkDatetime: "23/08/2022 14:20"
      },
      {
        id: 5,
        ticketNumber: 345678,
        result: true,
        checkDatetime: "23/08/2022 14:20"
      },
      {
        id: 6,
        ticketNumber: 222333,
        result: true,
        checkDatetime: "23/08/2022 14:20"
      }
    ])
  }, []);

  const renderTicketRow = (): ReactNode => {
    return tickets.map((ticket) => {
      return <tr key={ticket.id}>
        <td className="g-white border-b dark:bg-gray-800 dark:border-gray-700 py-3 px-6 border border-current">{ticket.ticketNumber}</td>
        <td className="g-white border-b dark:bg-gray-800 dark:border-gray-700 py-3 px-6 border border-current">{ticket.result ? "Good" : "Failed"}</td>
        <td className="g-white border-b dark:bg-gray-800 dark:border-gray-700 py-3 px-6 border border-current">{ticket.checkDatetime}</td>
      </tr>
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>List Ticket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl ">
          Ticket List
        </h1>
        <div className="overflow-x-auto relative">
          <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400 border border-current">
            <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <td scope="col" className="py-3 px-6 border border-current">Ticket Number</td>
                <td scope="col" className="py-3 px-6 border border-current">Result</td>
                <td scope="col" className="py-3 px-6 border border-current">Check Datetime</td>
              </tr>
            </thead>
            <tbody>
              {renderTicketRow()}
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
